# json-property-access integration test config
domains:
  - name: basic
    controllerPackage: com.example.controller
    reqDTOPackage: com.example.dto.req
    respDTOPackage: com.example.dto.resp
    enumPackage: com.example.enums
    servicePackage: com.example.service
    serviceImplPackage: com.example.service.impl
    mapperPackage: com.example.mapper
    entityPackage: com.example.entity
    designPackage: com.example.design
    paramDTOPackage: com.example.dto.param
    recordDTOPackage: com.example.dto.record
    wholeDTOPackage: com.example.dto

author: test-author
javaVersion: "8"
enableNoModifyAnnounce: true
enableJavaxMoveToJakarta: false
isDataModelWithoutLombok: false

flushTo:
  - MARKDOWN
markdownDir: api-docs
globalUrlPrefix: ""

codeSnippet:
  constructPageResult: "new PageResult<>(${total}, ${dtos})"
  constructEmptyPageResult: "new PageResult<>()"

