server:
  port: 8080

spring:
  application:
    name: __APP_NAME__
  datasource:
    url: __DATASOURCE_URL__/__DATASOURCE_SCHEMA__?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: __DATASOURCE_USERNAME__
    password: __DATASOURCE_PASSWORD__
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      static-locations: classpath:/static/

logging:
  config: classpath:logback-spring.xml

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    default-enum-type-handler: __NAMESPACE__.mybatis.EnumTypeHandlerEx

__APP_NAME__:
  authc:
    anonymousApiPaths: /api/v1/authc/login
    loginExpireTime: 172800000 # millis of 2 days
    disableMultiDeviceLogin: false